---
- name: Calico | Create calico manifests
  template:
    src: "{{item.file}}.j2"
    dest: "{{kube_config_dir}}/{{item.file}}"
  with_items:
    - {name: calico-rbac, file: calico-rbac.yml, type: cm}
    - {name: calico-node, file: calico-node.yml, type: ds}
  register: calico_node_manifests
  when:
    - inventory_hostname in groups['kube-master']
    - rbac_enabled

- name: Calico | Start Calico resources
  kube:
    namespace: "kube-system"
    kubectl: "{{bin_dir}}/kubectl"
    filename: "{{kube_config_dir}}/{{item.item.file}}"
    state: "latest"
  with_items: "{{ calico_node_manifests.results }}"
  when: inventory_hostname == groups['kube-master'][0]

- name: Calico | Install calicoctl container script
  template:
    src: calicoctl-container.j2
    dest: "{{ bin_dir }}/calicoctl"
    mode: 0755
    owner: root
    group: root
  when: inventory_hostname == groups['kube-master'][0]