---
- name: look up docker cgroup driver
  shell: "docker info | grep 'Cgroup Driver' | awk -F': ' '{ print $2; }'"
  register: docker_cgroup_driver_result
  changed_when: false

- name: Get bootstrap token value
  command: "awk -F',' '{print $1}' {{ kube_token_dir }}/known_tokens.csv"
  register: bootstrap_token_result
  changed_when: false
  delegate_to: "{{groups['kube-master'][0]}}"
  run_once: true
  
- set_fact:
    standalone_kubelet: >-
      {%- if inventory_hostname in groups['kube-master'] and inventory_hostname not in groups['kube-node'] -%}true{%- else -%}false{%- endif -%}
    kubelet_cgroup_driver_detected: "{{ docker_cgroup_driver_result.stdout }}"
    kube_bootstrap_token: "{{ bootstrap_token_result.stdout }}"
