---
docker_kernel_min_version: '3.10'

docker_versioned_pkg:
  'latest': docker-ce
  '17.03': docker-ce=17.03.2~ce-0~ubuntu-{{ ansible_distribution_release|lower }}
  'stable': docker-ce=17.03.2~ce-0~ubuntu-{{ ansible_distribution_release|lower }}
  'edge': docker-ce=17.12.1~ce-0~ubuntu-{{ ansible_distribution_release|lower }}

docker_package_info:
  pkg_mgr: apt
  pkgs:
    - name: "{{ docker_versioned_pkg[docker_version | string] }}"
      force: yes

docker_repo_info:
  pkg_repo: apt_repository
  repos:
    - >
       deb {{ docker_ubuntu_repo_base_url }}
       {{ ansible_distribution_release|lower }}
       stable
