---
- name: Install | Copy etcdctl binary from docker container
  command: sh -c "docker run --rm -i -v /usr/local/bin:/mnt {{ etcd_image_repo }}:{{ etcd_image_tag }} cp /usr/local/bin/etcdctl /mnt"
  register: etcd_task_result
  until: etcd_task_result.rc == 0
  retries: 4
  delay: "{{ retry_stagger | random + 3 }}"
  changed_when: false

- name: Install etcd launch script
  template:
    src: etcd.j2
    dest: "{{ bin_dir }}/etcd"
    owner: 'root'
    mode: 0755
    backup: yes
  notify: restart etcd

- name: Install | make sure data dir existed
  file:
    path: "{{ etcd_data_dir }}"
    state: directory