---
- import_tasks: check-certs.yml
  tags:
    - k8s-secrets
    - facts

- import_tasks: check-tokens.yml
  tags:
    - k8s-secrets
    - facts

- name: Make sure the certificate directory exits
  file:
    path: "{{ kube_cert_dir }}"
    state: directory
    mode: o-rwx
    group: "{{ kube_cert_group }}"

- name: Make sure the tokens directory exits
  file:
    path: "{{ kube_token_dir }}"
    state: directory
    mode: o-rwx
    group: "{{ kube_cert_group }}"


- include_tasks: "gen_certs_{{ cert_management }}.yml"
  tags:
    - k8s-secrets

- import_tasks: upd_ca_trust.yml
  tags:
    - k8s-secrets

- name: "Gen_certs | Get certificate serials on kube masters"
  shell: "openssl x509 -in {{ kube_cert_dir }}/{{ item }} -noout -serial | cut -d= -f2"
  register: "master_certificate_serials"
  changed_when: false
  with_items:
    - "admin.pem"
    - "apiserver.pem"
    - "kube-controller-manager.pem"
    - "kube-scheduler.pem"
  when: inventory_hostname in groups['kube-master']

- name: "Gen_certs | set kube master certificate serial facts"
  set_fact:
    etcd_admin_cert_serial: "{{ master_certificate_serials.results[0].stdout|default() }}"
    apiserver_cert_serial: "{{ master_certificate_serials.results[1].stdout|default() }}"
    controller_manager_cert_serial: "{{ master_certificate_serials.results[2].stdout|default() }}"
    scheduler_cert_serial: "{{ master_certificate_serials.results[3].stdout|default() }}"
  when: inventory_hostname in groups['kube-master']

- name: "Gen_certs | Get certificate serials on kube nodes"
  shell: "openssl x509 -in {{ kube_cert_dir }}/{{ item }} -noout -serial | cut -d= -f2"
  register: "node_certificate_serials"
  changed_when: false
  with_items:
    - "kube-proxy.pem"
  when: inventory_hostname in groups['k8s-cluster']

- name: "Gen_certs | set kube node certificate serial facts"
  set_fact:
    kube_proxy_cert_serial: "{{ node_certificate_serials.results[0].stdout|default() }}"
  when: inventory_hostname in groups['k8s-cluster']

- import_tasks: gen_tokens.yml
  tags:
    - k8s-secrets
