---

- name: Delete node
  command: kubectl delete node {{ item }}
  with_items:
    - "{{ groups['kube-node'] }}"
  delegate_to: "{{ groups['kube-master'][0] }}"
  run_once: true
  ignore_errors: yes
